config/routes.rb
Rails.application.routes.draw do

resources :hookups, only: [:new, :create, :show]
root to:  "hookups#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hookup.rb
class Hookup< ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hookups_controller.rb
class HookupsController < ApplicationController

  def index
    @hookups = Hookup.all
  end

  def new
    @hookup = Hookup.new
  end

  def create
    @hookup = Hookup.create(hookup_params)

    redirect_to @hookup
  end

  def show
    @hookup = Hookup.find(params[:id])
  end

  private

  def hookup_params
    params.require(:hookup).permit(:title, :url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hookups/index.html.erb
<%@hookups.each do |hookup|%>
<li>
  <%= link_to hookup.title, hookup.url %> 
  </li>
<%end%>
<%= link_to "Submit a new hookup", new_hookup_path %>

app/views/hookups/new.html.erb
<%= form_for @hookup do |form| %>
<%= form.text_field :title %>
<%= form.text_field :url %>
<%= form.submit "Submit!" %>
<% end %>

app/views/hookups/show.html.erb
<%= link_to @hookup.title, @hookup.url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>